django_acdhch_functions/urls.py
from django.urls import path

from . import views

app_name = "django_acdhch_functions"

urlpatterns = [path("imprint", views.Imprint.as_view(), name="imprint")]

django_acdhch_functions/views.py
from django.views.generic import TemplateView

from . import utils


class Imprint(TemplateView):
    template_name = "acdhch_functions/imprint.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["imprint"] = utils.get_impressum()
        return ctx

django_acdhch_functions/templates/acdhch_functions/imprint.html
{% extends basetemplate|default:"base.html" %}

{% block title %}Imprint{% endblock %}

{% block content %}
  <div class="container">
    <div class="card imprint">
      <div class="card-body">{{ imprint|safe }}</div>
    </div>
  </div>
{% endblock %}

django_acdhch_functions/templates/base.html
{% extends basetemplate|default:"base.html" %}
{% load django_acdhch_functions %}

{% block scriptHeader %}
  {{ block.super }}
  {% matomo %}
{% endblock scriptHeader %}

{% block imprint %}
  <div id="wrapper-footer-secondary"
       class="footer-imprint-bar p-2 text-center">
    <a href="{% url 'django_acdhch_functions:imprint' %}">Imprint | Impressum</a>
  </div>
{% endblock imprint %}

django_acdhch_functions/templates/matomo.html
{% if matomo_url and matomo_id %}
  <!-- Begin Matomo tracking -->
  <script type="text/javascript">
var _paq = _paq || [];
/* tracker methods like "setCustomDimension" should be called before "trackPageView" */
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
(function () {
  var u = "{{ matomo_url }}";
  _paq.push(['setTrackerUrl', u + 'piwik.php']);
  _paq.push(['setSiteId', '{{ matomo_id }}']);
  var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
  g.type = 'text/javascript';
  g.async = true;
  g.defer = true;
  g.src = u + 'piwik.js';
  s.parentNode.insertBefore(g, s);
})();
  </script>
  <!-- End Matomo tracking -->
{% else %}
  <!-- No matomo_id or matomo_url found %} -->
{% endif %}